$mainMod = SUPER
$terminal = ghostty
$fileManager = yazi

monitor=,preferred,auto,1.25

workspace = 1
workspace = 2
workspace = 3
workspace = 4 
workspace = 5
workspace = 6
workspace = 7
workspace = 8
workspace = 9

bind = $mainMod, Q, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $terminal -e $fileManager
bind = $mainMod, F, togglefloating,

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9

bind = $mainMod_SHIFT, 1, movetoworkspace, 1
bind = $mainMod_SHIFT, 2, movetoworkspace, 2
bind = $mainMod_SHIFT, 3, movetoworkspace, 3
bind = $mainMod_SHIFT, 4, movetoworkspace, 4
bind = $mainMod_SHIFT, 5, movetoworkspace, 5
bind = $mainMod_SHIFT, 6, movetoworkspace, 6
bind = $mainMod_SHIFT, 7, movetoworkspace, 7
bind = $mainMod_SHIFT, 8, movetoworkspace, 8
bind = $mainMod_SHIFT, 9, movetoworkspace, 9

bind = $mainMod_SHIFT, h, swapwindow, l
bind = $mainMod_SHIFT, l, swapwindow, r
bind = $mainMod_SHIFT, k, swapwindow, u
bind = $mainMod_SHIFT, j, swapwindow, d

bind = , XF86MonBrightnessUp, exec, brightnessctl set +5%
bind = , XF86MonBrightnessDown, exec, brightnessctl set 5%-

bind = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ --limit 1.0
bind = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

bind = , XF86TouchpadToggle, exec, ~/.config/hypr/scripts/toggle_touchpad.sh

$slurp_conf = "$(slurp -b 00000080 -c 000000FF -s 00000000)" 
bind = , Print, exec, grim -g $slurp_conf - | satty --filename -
bind = $mainMod_SHIFT, T, exec, grim -g $slurp_conf /tmp/ocr.png && tesseract /tmp/ocr.png stdout -l ind+eng | wl-copy

bind = ALT, SPACE, exec, fuzzel
bind = $mainMod, l, exec, hyprlock

bind = $mainMod_SHIFT, c, exec, hyprpicker -a
bind = $mainMod, v, exec, cliphist list | fuzzel --dmenu | cliphist decode | wl-copy

exec-once = hyprpaper
exec-once = waybar
exec-once = hypridle

exec-once = gpg-agent --daemon

exec-once = /usr/lib/xdg-desktop-portal
exec-once = /usr/lib/polkit-kde-authentication-agent-1

exec-once = hyprctl keyword "device[asue1201:00-04f3:3125-touchpad]:enabled" false

exec-once = [workspace 1 silent] $terminal -e btop
exec-once = [workspace 2 silent] $terminal -e $fileManager
exec-once = [workspace 3 silent] $terminal
exec-once = [workspace 4 silent] ai
exec-once = [workspace 8 silent] chat
exec-once = [workspace 9 silent] $terminal -e aerc

env = MOZ_ENABLE_WAYLAND,1

windowrule {
    name = pengaturan-satty
    match:class = com.gabm.satty
    float = on
    center = on
    size = (monitor_w*0.8) (monitor_h*0.8)
}

general {
	gaps_in = 2
	gaps_out = 5
	border_size = 0
}

decoration {
	inactive_opacity = 0.9
	active_opacity = 1
	fullscreen_opacity = 1
}

xwayland {
	force_zero_scaling = true
}
